# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.CharField(max_length=255)),
                ('publish_date', models.CharField(max_length=255)),
                ('blog_title', models.CharField(max_length=20)),
                ('blog_content', models.CharField(max_length=1024)),
            ],
        ),
    ]
